language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'

script:
  - composer install
  - vendor/bin/phpunit

cache:
  directories:
    - "$HOME/.composer"
    - "$HOME/.cache/composer"
    - "$HOME/.composer/cache"