#!/usr/bin/php
<?php
/**
 *    ______            __             __
 *   / ____/___  ____  / /__________  / /
 *  / /   / __ \/ __ \/ __/ ___/ __ \/ /
 * / /___/ /_/ / / / / /_/ /  / /_/ / /
 * \______________/_/\__/_/   \____/_/
 *    /   |  / / /_
 *   / /| | / / __/
 *  / ___ |/ / /_
 * /_/ _|||_/\__/ __     __
 *    / __ \___  / /__  / /____
 *   / / / / _ \/ / _ \/ __/ _ \
 *  / /_/ /  __/ /  __/ /_/  __/
 * /_____/\___/_/\___/\__/\___/
 *
 */

namespace ControlAltDelete\Shorty;

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$application = new \Symfony\Component\Console\Application();

$application->addCommands([
    app()->make(\ControlAltDelete\Shorty\Commands\AddCommand::class),
    app()->make(\ControlAltDelete\Shorty\Commands\GlobalCommand::class),
    app()->make(\ControlAltDelete\Shorty\Commands\DeleteCommand::class),
    app()->make(\ControlAltDelete\Shorty\Commands\FixCommand::class),
]);

$application->run();
